services:
  - type: web
    name: duochat
    env: node
    plan: free
    region: oregon
    branch: master
    buildCommand: npm install && node scripts/migrate-push.js && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: VAPID_EMAIL
        value: mailto:info@duochat.app
      - key: NEXT_PUBLIC_VAPID_PUBLIC_KEY
        sync: false
    autoDeploy: true
